### ISSUE TITLE
torrenttrader.xyz

### ISSUE THREAD

**Issue by STX2k** [MicrosoulV3/torrenttrader-3.0#1]
Reg is buggy @ torrenttrader.xyz i get an internal error if i try to reg.

**Comment by xbladecod3r** [comment]
Yes u will its not a true mysqli mate its v2 not v3

**Comment by MicrosoulV3** [comment]
Im not sure why that would happen. The site is running. Just try again. Perhaps it was down for mainteinance.

**Comment by STX2k** [comment]
mhh. I try it again and get this error:

Oops! We ran into some problems.
A server error occurred. Please try again later.

**Comment by MicrosoulV3** [comment]
hmm, very odd. I will let the site admin know about it. So you are able to get to the site but you cant register? Is that correct?

**Comment by STX2k** [comment]
Yes i can not register.

**Comment by xbladecod3r** [comment]
its a very bad site to go too its full of want to be coder who know nothing about coding and mysqli

**Comment by xbladecod3r** [comment]
this is a want to be coder who knows nothing about coding mysqli a ban not stop me from posting ok



Sent from Yahoo Mail. Get the app 

    On Friday, 5 April 2019, 18:58:56 BST, STX <notifications@github.com> wrote:  
 
 
Yes i can not register.

**Comment by MicrosoulV3** [comment]
the site owners said they are looking onto it. Just keep trying randomly as I dont know when they will have it working as I dont know why it would do that.
