### ISSUE TITLE
This not v3 its v2 with a no way msqli

### ISSUE THREAD

**Issue by xbladecod3r** [MicrosoulV3/torrenttrader-3.0#2]
its not mysqli hes a want to be coder

**Comment by xbladecod3r** [comment]
This not the v3 its v2 of torrenttrader v2 the mysqli is very bad coding and the mods hes making for it also M-jay its a mess too he can not code all the base core of hes so called v3 is one mass beware this not a full mysqli very bad coding ... my him self... if you want a Good v3 with a proper mysqli send me a mass via mass on here and i can do this for you and mysqli and mods

**Comment by MicrosoulV3** [comment]
I let this comment stay here so people can see what complete stupidity looks like when it gets typed on a comment section
